---P1 ACADEMIC STANDING---
SELECT SHRTTRM_PIDM
FROM SHRTTRM, GTVSDAX
WHERE 1=1
AND GTVSDAX_INTERNAL_CODE = 'CURR_TERM'
AND GTVSDAX_INTERNAL_CODE_GROUP = 'OBU'
AND GTVSDAX_EXTERNAL_CODE = SHRTTRM_TERM_CODE
AND SHRTTRM_ASTD_CODE_END_OF_TERM = 'P1'
AND NOT EXISTS 
(SELECT 'C' 
FROM GCRCITM 
WHERE TRUNC(GCRCITM_SENT_DATE) = TRUNC(SYSDATE)
AND GCRCITM_TEMPLATE_ID = 36)
;

---P1 STUDY PATH ACADEMIC STANDING---
SELECT SHRAPSP_PIDM
FROM SHRAPSP, GTVSDAX
WHERE 1=1
AND GTVSDAX_INTERNAL_CODE = 'CURR_TERM'
AND GTVSDAX_INTERNAL_CODE_GROUP = 'OBU'
AND SHRAPSP_TERM_CODE = GTVSDAX_EXTERNAL_CODE
AND SHRAPSP_ASTD_CODE_END_OF_TERM = 'P1'
AND NOT EXISTS 
(SELECT 'C' 
FROM GCRCITM 
WHERE TRUNC(GCRCITM_SENT_DATE) = TRUNC(SYSDATE)
AND GCRCITM_TEMPLATE_ID = 36)
;

---P2 Can Progress: Compensation Applied: (All UG Academic Framework students only, Sept 2020 onwards)---
SELECT SHRAPSP_PIDM
FROM SHRAPSP, SORLCUR, GTVSDAX
WHERE 1=1
AND SHRAPSP_PIDM = SORLCUR_PIDM
and (SORLCUR_LMOD_CODE = 'LEARNER'
AND SORLCUR_CACT_CODE = 'ACTIVE'
AND SORLCUR_TERM_CODE_END IS NULL
AND SORLCUR_CURRENT_CDE = 'Y'
AND SORLCUR_LEVL_CODE = 'UG'
AND SORLCUR_TERM_CODE_ADMIT >= 202009)
AND GTVSDAX_INTERNAL_CODE = 'CURR_TERM'
AND GTVSDAX_INTERNAL_CODE_GROUP = 'OBU'
AND SHRAPSP_TERM_CODE = GTVSDAX_EXTERNAL_CODE
AND SHRAPSP_ASTD_CODE_END_OF_TERM = 'P2'
;

--->P3 Cannot Progress: Continue on Current Award (UG & PG, Non-Tier 4) 
SELECT SHRAPSP_PIDM
FROM SHRAPSP, SORLCUR, GTVSDAX
WHERE 1=1
AND SHRAPSP_PIDM = SORLCUR_PIDM
and (SORLCUR_LMOD_CODE = 'LEARNER'
AND SORLCUR_CACT_CODE = 'ACTIVE'
AND SORLCUR_TERM_CODE_END IS NULL
AND SORLCUR_CURRENT_CDE = 'Y'
AND SORLCUR_LEVL_CODE IN ('UG', 'PG'))
AND GTVSDAX_INTERNAL_CODE = 'CURR_TERM'
AND GTVSDAX_INTERNAL_CODE_GROUP = 'OBU'
AND SHRAPSP_TERM_CODE = GTVSDAX_EXTERNAL_CODE
AND SHRAPSP_ASTD_CODE_END_OF_TERM = 'P3'
AND (SHRAPSP_PIDM NOT IN
    (SELECT GORVISA_PIDM
    FROM GORVISA)
OR SHRAPSP_PIDM NOT IN
    (SELECT GORVISA_PIDM
    FROM GORVISA
    WHERE 1=1
    AND GORVISA_PIDM = SHRAPSP_PIDM
    AND GORVISA_VTYP_CODE = 'T4'))
;


---P3 Cannot Progress: Continue on Current Award (UG & PG, Tier 4) 
SELECT SHRAPSP_PIDM
FROM SHRAPSP, SORLCUR, GTVSDAX
WHERE 1=1
AND SHRAPSP_PIDM = SORLCUR_PIDM
and (SORLCUR_LMOD_CODE = 'LEARNER'
AND SORLCUR_CACT_CODE = 'ACTIVE'
AND SORLCUR_TERM_CODE_END IS NULL
AND SORLCUR_CURRENT_CDE = 'Y'
AND SORLCUR_LEVL_CODE IN ('UG', 'PG'))
AND GTVSDAX_INTERNAL_CODE = 'CURR_TERM'
AND GTVSDAX_INTERNAL_CODE_GROUP = 'OBU'
AND SHRAPSP_TERM_CODE = 201901
---AND SHRAPSP_TERM_CODE = GTVSDAX_EXTERNAL_CODE
AND SHRAPSP_ASTD_CODE_END_OF_TERM = 'P3'
AND SHRAPSP_PIDM =
    (SELECT DISTINCT GORVISA_PIDM
    FROM GORVISA
    WHERE 1=1
    AND GORVISA_PIDM = SHRAPSP_PIDM
    AND GORVISA_VTYP_CODE = 'T4')
;


---P3 Cannot Progress: Continue on Current Award (Foundation, All) 
SELECT SHRAPSP_PIDM
FROM SHRAPSP, SORLCUR, GTVSDAX
WHERE 1=1
AND SHRAPSP_PIDM = SORLCUR_PIDM
and (SORLCUR_LMOD_CODE = 'LEARNER'
AND SORLCUR_CACT_CODE = 'ACTIVE'
AND SORLCUR_TERM_CODE_END IS NULL
AND SORLCUR_CURRENT_CDE = 'Y'
AND SORLCUR_LEVL_CODE = 'FD')
AND GTVSDAX_INTERNAL_CODE = 'CURR_TERM'
AND GTVSDAX_INTERNAL_CODE_GROUP = 'OBU'
AND SHRAPSP_TERM_CODE = GTVSDAX_EXTERNAL_CODE
AND SHRAPSP_ASTD_CODE_END_OF_TERM = 'P3'
;


---P4 Cannot Progress: Continue on Lower Award (UG & PG, Non-Tier 4)
SELECT SHRAPSP_PIDM
FROM SHRAPSP, SORLCUR, GTVSDAX
WHERE 1=1
AND SHRAPSP_PIDM = SORLCUR_PIDM
and (SORLCUR_LMOD_CODE = 'LEARNER'
AND SORLCUR_CACT_CODE = 'ACTIVE'
AND SORLCUR_TERM_CODE_END IS NULL
AND SORLCUR_CURRENT_CDE = 'Y'
AND SORLCUR_LEVL_CODE IN ('UG', 'PG'))
AND GTVSDAX_INTERNAL_CODE = 'CURR_TERM'
AND GTVSDAX_INTERNAL_CODE_GROUP = 'OBU'
AND SHRAPSP_TERM_CODE = GTVSDAX_EXTERNAL_CODE
AND SHRAPSP_ASTD_CODE_END_OF_TERM = 'P4'
AND (SHRAPSP_PIDM NOT IN
    (SELECT GORVISA_PIDM
    FROM GORVISA)
OR SHRAPSP_PIDM NOT IN
    (SELECT GORVISA_PIDM
    FROM GORVISA
    WHERE 1=1
    AND GORVISA_PIDM = SHRAPSP_PIDM
    AND GORVISA_VTYP_CODE = 'T4'))
;


---P4 Cannot Progress: Continue on Lower Award (UG & PG, Tier 4)
SELECT SHRAPSP_PIDM
FROM SHRAPSP, SORLCUR, GTVSDAX
WHERE 1=1
AND SHRAPSP_PIDM = SORLCUR_PIDM
and (SORLCUR_LMOD_CODE = 'LEARNER'
AND SORLCUR_CACT_CODE = 'ACTIVE'
AND SORLCUR_TERM_CODE_END IS NULL
AND SORLCUR_CURRENT_CDE = 'Y'
AND SORLCUR_LEVL_CODE IN ('UG', 'PG'))
AND GTVSDAX_INTERNAL_CODE = 'CURR_TERM'
AND GTVSDAX_INTERNAL_CODE_GROUP = 'OBU'
AND SHRAPSP_TERM_CODE = GTVSDAX_EXTERNAL_CODE
AND SHRAPSP_ASTD_CODE_END_OF_TERM = 'P4'
AND SHRAPSP_PIDM =
    (SELECT DISTINCT GORVISA_PIDM
    FROM GORVISA
    WHERE 1=1
    AND GORVISA_PIDM = SHRAPSP_PIDM
    AND GORVISA_VTYP_CODE = 'T4')
;


---T1: Can progress: trailing modules (UG (pre academic framework only)& PG)
SELECT DISTINCT SHRAPSP_PIDM
FROM SHRAPSP, SORLCUR, GTVSDAX
WHERE 1=1
AND SHRAPSP_PIDM = SORLCUR_PIDM
and (SORLCUR_LMOD_CODE = 'LEARNER'
AND SORLCUR_CACT_CODE = 'ACTIVE'
AND SORLCUR_TERM_CODE_END IS NULL
AND SORLCUR_CURRENT_CDE = 'Y')
AND ((SORLCUR_LEVL_CODE = 'UG'
AND SORLCUR_TERM_CODE_ADMIT < 202009)
OR (SORLCUR_LEVL_CODE = 'PG'))
AND GTVSDAX_INTERNAL_CODE = 'CURR_TERM'
AND GTVSDAX_INTERNAL_CODE_GROUP = 'OBU'
AND SHRAPSP_TERM_CODE = GTVSDAX_EXTERNAL_CODE
AND SHRAPSP_ASTD_CODE_END_OF_TERM = 'T1'
;


--->G2 Does Not Qualify: Continue on Current Award (UG & PG, Non-Tier 4)
SELECT SHRAPSP_PIDM
FROM SHRAPSP, SORLCUR, GTVSDAX
WHERE 1=1
AND SHRAPSP_PIDM = SORLCUR_PIDM
and (SORLCUR_LMOD_CODE = 'LEARNER'
AND SORLCUR_CACT_CODE = 'ACTIVE'
AND SORLCUR_TERM_CODE_END IS NULL
AND SORLCUR_CURRENT_CDE = 'Y'
AND SORLCUR_LEVL_CODE IN ('UG', 'PG'))
AND GTVSDAX_INTERNAL_CODE = 'CURR_TERM'
AND GTVSDAX_INTERNAL_CODE_GROUP = 'OBU'
AND SHRAPSP_TERM_CODE = GTVSDAX_EXTERNAL_CODE
AND SHRAPSP_ASTD_CODE_END_OF_TERM = 'G2'
AND (SHRAPSP_PIDM NOT IN
    (SELECT GORVISA_PIDM
    FROM GORVISA)
OR SHRAPSP_PIDM NOT IN
    (SELECT GORVISA_PIDM
    FROM GORVISA
    WHERE 1=1
    AND GORVISA_PIDM = SHRAPSP_PIDM
    AND GORVISA_VTYP_CODE = 'T4'))
;


---G2 Does Not Qualify: Continue on Current Award (UG & PG, Tier 4)
SELECT SHRAPSP_PIDM
FROM SHRAPSP, SORLCUR, GTVSDAX
WHERE 1=1
AND SHRAPSP_PIDM = SORLCUR_PIDM
AND (SORLCUR_LMOD_CODE = 'LEARNER'
AND SORLCUR_CACT_CODE = 'ACTIVE'
AND SORLCUR_TERM_CODE_END IS NULL
AND SORLCUR_CURRENT_CDE = 'Y'
AND SORLCUR_LEVL_CODE IN ('UG', 'PG'))
AND GTVSDAX_INTERNAL_CODE = 'CURR_TERM'
AND GTVSDAX_INTERNAL_CODE_GROUP = 'OBU'
AND SHRAPSP_TERM_CODE = GTVSDAX_EXTERNAL_CODE
AND SHRAPSP_ASTD_CODE_END_OF_TERM = 'G2'
AND SHRAPSP_PIDM =
    (SELECT DISTINCT GORVISA_PIDM
    FROM GORVISA
    WHERE 1=1
    AND GORVISA_PIDM = SHRAPSP_PIDM
    AND GORVISA_VTYP_CODE = 'T4')
;


---D3 Decision Deferred: Pending Resits (All, excluding Healthcare)
SELECT SHRAPSP_PIDM
FROM SHRAPSP, SORLCUR, GTVSDAX
WHERE 1=1
AND (SORLCUR_LMOD_CODE = 'LEARNER'
AND SORLCUR_CACT_CODE = 'ACTIVE'
AND SORLCUR_TERM_CODE_END IS NULL
AND SORLCUR_CURRENT_CDE = 'Y'
AND SORLCUR_COLL_CODE != 'HL')
AND GTVSDAX_INTERNAL_CODE = 'CURR_TERM'
AND GTVSDAX_INTERNAL_CODE_GROUP = 'OBU'
AND SHRAPSP_TERM_CODE = GTVSDAX_EXTERNAL_CODE
AND SHRAPSP_ASTD_CODE_END_OF_TERM = 'D3'
;

---D3 Decision Deferred: Pending Resits (UG, Healthcare)
SELECT SHRAPSP_PIDM
FROM SHRAPSP, SORLCUR, GTVSDAX
WHERE 1=1
AND (SORLCUR_LMOD_CODE = 'LEARNER'
AND SORLCUR_CACT_CODE = 'ACTIVE'
AND SORLCUR_TERM_CODE_END IS NULL
AND SORLCUR_CURRENT_CDE = 'Y'
AND SORLCUR_COLL_CODE = 'HL')
AND GTVSDAX_INTERNAL_CODE = 'CURR_TERM'
AND GTVSDAX_INTERNAL_CODE_GROUP = 'OBU'
AND SHRAPSP_TERM_CODE = GTVSDAX_EXTERNAL_CODE
AND SHRAPSP_ASTD_CODE_END_OF_TERM = 'D3'
;


---AF ACADEMIC FAILURE:(UG/PG, Non-Tier 4, Tier4)---
SELECT SHRAPSP_PIDM
FROM SHRAPSP, SORLCUR, GTVSDAX
WHERE 1=1
AND SHRAPSP_PIDM = SORLCUR_PIDM
AND SHRAPSP_STSP_KEY_SEQUENCE = SORLCUR_KEY_SEQNO
AND (SORLCUR_LMOD_CODE = 'LEARNER'
AND SORLCUR_CACT_CODE = 'ACTIVE'
AND SORLCUR_TERM_CODE_END IS NULL)
AND SORLCUR_LEVL_CODE IN ('UG', 'PG')
AND (GTVSDAX_INTERNAL_CODE = 'CURR_TERM'
AND GTVSDAX_INTERNAL_CODE_GROUP = 'OBU')
AND SHRAPSP_TERM_CODE = GTVSDAX_EXTERNAL_CODE
AND SHRAPSP_ASTD_CODE_END_OF_TERM = 'AF'
ORDER BY SHRAPSP_TERM_CODE
;



---C1 CONGRATULATIONS: UG, TIER 4 AND NON-TIER4 AWARDED 1ST CLASS DEGREE---
SELECT SHRDGIH_PIDM
FROM SHRDGMR, SHRDGIH
WHERE 1=1
AND SHRDGMR_PIDM = SHRDGIH_PIDM
AND SHRDGMR_SEQ_NO = SHRDGIH_DGMR_SEQ_NO
AND SHRDGMR_DEGS_CODE IN ('PN', 'AW')
AND SHRDGMR_LEVL_CODE = 'UG'
AND SHRDGIH_HONR_CODE = 'FIRST'
---AND SHRDGMR_TERM_CODE_GRAD IS NULL
---AND SHRDGMR_ACYR_CODE IS NULL
AND SHRDGMR_GRAD_DATE >= '01-AUG-19'
ORDER BY SHRDGMR_PIDM
;


---C1 CONGRATULATIONS:  AWARDED - PG, TIER 4 AND NON-TIER4---
SELECT SHRDGIH_PIDM
FROM SHRDGMR, SHRDGIH
WHERE 1=1
AND SHRDGMR_PIDM = SHRDGIH_PIDM
AND SHRDGMR_SEQ_NO = SHRDGIH_DGMR_SEQ_NO
AND SHRDGMR_DEGS_CODE IN ('PN', 'AW')
AND SHRDGMR_LEVL_CODE = 'PG'
---AND SHRDGMR_TERM_CODE_GRAD IS NULL
---AND SHRDGMR_ACYR_CODE IS NULL
AND SHRDGMR_GRAD_DATE >= '01-AUG-19'
ORDER BY SHRDGMR_PIDM
;