select distinct
SCBCRSE_COLL_CODE,
SSBSECT_PTRM_CODE,
SSBSECT_SUBJ_CODE,
SSBSECT_CRSE_NUMB,
SCBCRSE_TITLE,
SHRGCOM_NAME,
SHRGCOM_DESCRIPTION,
SHRGCOM_WEIGHT,
SHRGCOM_TOTAL_SCORE,
SHRGCOM_PASS_IND,
SHRGCOM_GRADE_SCALE,
SHRGCOM_COMP_RESIT_RULE
from
SSBSECT,
SHRGCOM,
SCBCRSE
where
SSBSECT_CRN = SHRGCOM_CRN(+)
and SCBCRSE_SUBJ_CODE = SSBSECT_SUBJ_CODE
and SCBCRSE_CRSE_NUMB = SSBSECT_CRSE_NUMB
and SSBSECT_CAMP_CODE in ('OBO', 'OBS', 'DL')
and SHRGCOM_TERM_CODE(+) = SSBSECT_TERM_CODE
and SSBSECT_TERM_CODE in ('201909','202001','202006')
and SSBSECT_SUBJ_CODE not in ('FEE', 'EXCH')
--and SSBSECT_SUBJ_CODE||SSBSECT_CRSE_NUMB = 'ACAD4001'
and SHRGCOM_NAME is null
--and SCBCRSE_COLL_CODE = 'HL'
order by
SCBCRSE_COLL_CODE,
SSBSECT_SUBJ_CODE,
SSBSECT_CRSE_NUMB
